.PHONY: all vet sec staticcheck test build

all: vet sec staticcheck test build

vet:            ; go vet ./...
sec:            ; gosec -exclude-dir=test ./...
#staticcheck:    ; staticcheck -config=.staticcheck.conf ./...
test:           ; go test ./test/...
build:          ; go build -o bin/goiam ./cmd