realm: customers
realm_name: Our beautiful Customers xoxo
base_url: http://localhost:8080/acme/customers

flows:
  login:
    route: /login
    active: yes
    debug_allowed: yes
    definition_location: login.yaml
  register:
    route: /register
    active: yes
    debug_allowed: yes
    definition_location: register.yaml
  unlock_account:
    route: /unlock-account
    active: no
    debug_allowed: yes
    definition_location: unlock_account.yaml
  totp-test:
    route: /totp-test
    active: yes
    debug_allowed: yes
    definition_location: totp-test.yaml

applications:
  customers-app:
    client_id: customers-app
    client_secret: customers-app-secret
