realm: customers
realm_name: Our beautiful Customers xoxo

flows:
  username-password-register:
    route: /username-password-register
    active: yes
    debug_allowed: yes
    definition_location: username-password-register.yaml
  username-password-login:
    route: /username-password-login
    active: yes
    debug_allowed: yes
    definition_location: username-password-login.yaml
  email-password-register:
    route: /email-password-register
    active: yes
    debug_allowed: yes
    definition_location: email-password-register.yaml
  email-password-login:
    route: /email-password-login
    active: yes
    debug_allowed: yes
    definition_location: email-password-login.yaml
  username-password-totp:
    route: /username-password-totp
    active: yes
    debug_allowed: yes
    definition_location: username-password-totp.yaml
  username-password-passkey-upgrade-login:
    route: /username-password-passkey-upgrade-login
    active: yes
    debug_allowed: yes
    definition_location: username-password-passkey-upgrade-login.yaml
  passkey_discovery_or_password:
    route: /passkey-discovery-or-password
    active: yes
    debug_allowed: yes
    definition_location: passkey_discovery_or_password.yaml
  error:
    route: /error
    active: yes
    debug_allowed: yes
    definition_location: error.yaml
  error2:
    route: /error2
    active: yes
    debug_allowed: yes
    definition_location: error2.yaml
  github-login:
    route: /github-login
    active: yes
    debug_allowed: yes
    definition_location: github-login.yaml
  mock_success:
    route: /mock-success
    active: yes
    debug_allowed: yes
    definition_location: mock_success.yaml
  mock_failure:
    route: /mock-failure
    active: yes
    debug_allowed: yes
    definition_location: mock_failure.yaml
  username-password-yubikey:
    route: /username-password-yubikey
    active: yes
    debug_allowed: yes
    definition_location: username-password-yubikey.yaml
  yubikey-only:
    route: /yubikey-only
    active: yes
    debug_allowed: yes
    definition_location: yubikey-only.yaml

applications:
  customers-app:
    client_id: customers-app
    client_secret: customers-app-secret
