realm: customers
realm_name: Our beautiful Customers xoxo
base_url: http://localhost:8080/acme/customers

flows:
  username-password-register:
    route: /username-password-register
    active: yes
    debug_allowed: yes
    definition_location: username-password-register.yaml
  username-password-login:
    route: /username-password-login
    active: yes
    debug_allowed: yes
    definition_location: username-password-login.yaml
  email-password-register:
    route: /email-password-register
    active: yes
    debug_allowed: yes
    definition_location: email-password-register.yaml
  email-password-login:
    route: /email-password-login
    active: yes
    debug_allowed: yes
    definition_location: email-password-login.yaml
  username-password-totp:
    route: /username-password-totp
    active: yes
    debug_allowed: yes
    definition_location: username-password-totp.yaml

applications:
  customers-app:
    client_id: customers-app
    client_secret: customers-app-secret
