apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "goam.fullname" . }}
  labels:
    {{- include "goam.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "goam.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "goam.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      containers:
        - name: goiam
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: /app/goam.yaml
              subPath: goam.yaml
          # We can also use env vars to override
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "goam.fullname" . }}-config