name: test_passkeys_registration
route: /test_create_passkeys
start: init
nodes:
  init:
    use: init
    next:
      start: setVariable
  setVariable:
    use: setVariable
    custom_config:
      key: username
      value: admin
    next:
      done: registerPasskey
  registerPasskey:
    use: registerPasskey
    next:
      success: finish
  finish:
    use: successResult