description: ''
start: init
nodes:
  init:
    name: init
    use: init
    custom_config: {}
    next:
      start: askEmail
      
  askEmail:
    name: askEmail
    use: askEmail
    custom_config:
      message: Please register your account
    next:
      submitted: emailOTP

  emailOTP:
    name: emailOTP
    use: emailOTP
    custom_config:
      init_user: true
      resend_in_seconds: 10
    next:
      success-registered-email: successResult
      success-unkown-email: successResult
  
  failureResult:
    name: failureResult
    use: failureResult
    custom_config:
      message: "Failed to login with Email OTP"
    next: {}
    
  successResult:
    name: successResult
    use: successResult
    custom_config:
      message: Login with Email OTP successful
    next: {}