description: ''
start: init
nodes:
  init:
    name: init
    use: init
    custom_config: {}
    next:
      start: askEmailPassword 
      
  askEmailPassword:
    name: askEmailPassword
    use: askEmailPassword
    custom_config:
      message: Please login to your account
    next:
      submitted: validatePassword

  validatePassword:
    name: validatePassword
    use: validatePassword
    custom_config: {}
    next:
      success: successResult
      fail: askEmailPassword
      locked: failureResult
      noPassword: failureResult

  
  failureResult:
    name: failureResult
    use: failureResult
    custom_config:
      message: Failed to login.
    next: {}
    
  successResult:
    name: successResult
    use: successResult
    custom_config:
      message: Login successful!
    next: {}