description: ''
start: init
nodes:
  init:
    name: init
    use: init
    custom_config: {}
    next:
      start: askEmail
      
  askEmail:
    name: askEmail
    use: askEmail
    custom_config:
      message: Please register your account
    next:
      submitted: checkEmailAvailable

  checkEmailAvailable:
    name: checkEmailAvailable
    use: checkEmailAvailable
    custom_config: {}
    next:
      available: askPassword
      taken: askEmail

  askPassword:
    name: askPassword
    use: askPassword
    custom_config:
      message: Please register your account
    next:
      submitted: createUser

  createUser:
    name: createUser
    use: createUser
    custom_config: {}
    next:
      fail: failureResult
      success: successResult
  
  failureResult:
    name: failureResult
    use: failureResult
    custom_config:
      message: Failed to create user. Email may already exist.
    next: {}
    
  successResult:
    name: successResult
    use: successResult
    custom_config:
      message: Registration successful!
    next: {}