description: 'This flow is used to test the error template'
start: init
nodes:
  init:
    name: init
    use: init
    custom_config: {}
    next:
      start: telegramLogin 

  telegramLogin:
    name: telegramLogin
    use: telegramLogin
    custom_config:
      telegram_bottoken:  "invalid" #Empty bot token will result in an execution error
    next:
      existing-user: successResult
      new-user: successResult
      failure: successResult