description: ''
start: init
nodes:
  askPassword:
    name: askPassword
    use: askPassword
    next:
      submitted: validateUsernamePassword
  askUsername:
    name: askUsername
    use: askUsername
    next:
      submitted: checkPasskeyRegistered
  authFailure:
    name: failureResult
    use: failureResult
    next: {}
  authSuccess:
    name: successResult
    use: successResult
    next: {}
  checkPasskeyRegistered:
    name: checkPasskeyRegistered
    use: checkPasskeyRegistered
    next:
      not_registered: askPassword
      registered: verifyPasskey
      user_not_found: authFailure
  init:
    name: init
    use: init
    next:
      start: askUsername
  validateUsernamePassword:
    name: validateUsernamePassword
    use: validateUsernamePassword
    next:
      fail: askPassword
      locked: authFailure
      success: authSuccess
  verifyPasskey:
    name: verifyPasskey
    use: verifyPasskey
    next:
      failure: authFailure
      success: authSuccess
editor:
  nodes:
    askPassword:
      x: 1066
      'y': -83.77463861668271
    askUsername:
      x: 154
      'y': -52
    authFailure:
      x: 1996.4
      'y': 344
    authSuccess:
      x: 2007.6
      'y': -212
    checkPasskeyRegistered:
      x: 506
      'y': -150
    init:
      x: -20.399999999999977
      'y': -34
    validateUsernamePassword:
      x: 1528
      'y': -34.40000000000009
    verifyPasskey:
      x: 1068
      'y': -256.8
