description: 'Choose between Mock OIDC and Google for authentication'
start: init
nodes:
  init:
    name: init
    use: init
    next:
      start: options

  options:
    name: options
    use: passwordOrSocialLogin
    custom_config:
      social1: "Mock OIDC"
      social2: "Google"
      title: "Choose Provider"
      message: "Please select an authentication provider"
      useUsername: "false"
      usePassword: "false"
    next:
      social1: mockOidcLogin
      social2: googleOidcLogin

  mockOidcLogin:
    name: mockOidcLogin
    use: genericOIDCLogin
    config_prefix: oidc_mock_
    custom_config:
      oidc_mock_issuer: http://localhost:8081/oidcconformancetest/customers
      oidc_mock_client_id: oidc-federation-test
      oidc_mock_client_secret: oidc-federation-test-secret
      oidc_mock_scope: "openid email profile"
    next:
      oidc_new_user: createUser
      oidc_existing_user: successResult
      oidc_failure: failureResult

  googleOidcLogin:
    name: googleOidcLogin
    use: genericOIDCLogin
    config_prefix: oidc_google_
    custom_config:
      oidc_google_issuer: https://accounts.google.com
      oidc_google_client_id: "1099505135701-4lsuqir3ul33ipgoqeli2ahsiu4mvplo.apps.googleusercontent.com"
      oidc_google_scope: "openid email profile"
    next:
      oidc_new_user: createUser
      oidc_existing_user: successResult
      oidc_failure: failureResult
    
  createUser:
    name: createUser
    use: createUser
    next:
      success: successResult
      existing: successResult

  successResult:
    name: successResult
    use: successResult
    custom_config:
      message: OIDC login successful!
    next: {}

  failureResult:
    name: failureResult
    use: successResult # Use success for failure here so we can see the error in the UI
    custom_config:
      message: OIDC login failed!
    next: {}