description: 'Login with both passkey discovery and password'
start: init
nodes:
  init:
    name: init
    use: init
    custom_config: {}
    next:
      start: passwordOrSocialLogin 
      
  passwordOrSocialLogin:
    name: passwordOrSocialLogin
    use: passwordOrSocialLogin
    custom_config:
      useUsername: true
      usePassword: true
      usePasskeys: true
      disablePasskeyBtn: true
      showRegistrationLink: true
      title: "Welcome back"
      message: "Try passkey discovery or password"
    next:
      password: validatePassword
      passkey: verifyPasskey

  validatePassword:
    name: validatePassword
    use: validatePassword
    custom_config: {}
    next:
      success: successResult
      fail: passwordOrSocialLogin
      locked: failureResult
      noPassword: failureResult

  verifyPasskey:
    name: verifyPasskey
    use: verifyPasskey
    custom_config: {}
    next:
      success: successResult
      failure: failureResult
  
  failureResult:
    name: failureResult
    use: failureResult
    custom_config:
      message: Failed to login.
    next: {}
    
  successResult:
    name: successResult
    use: successResult
    custom_config:
      message: Login successful!
    next: {}