flow_id: unlock_account
route: unlockAccount
active: yes

definition:
  name: "Unlock Account"
  description: "Account unlocking flow not secure, only for testing purposes"

  start: init
  nodes:
    init:
      use: init
      next:
        start: askUsername

    askUsername:
      use: askUsername
      next:
        submitted: unlockAccount
      custom_config:
        message: Enter username to unlock your account

    unlockAccount:
      use: unlockAccount
      next:
        success: unlockSuccess
        fail: unlockFailure

    unlockSuccess:
      use: successResult
      custom_config:
        message: "The account has been successfully unlocked."

    unlockFailure:
      use: failureResult
      custom_config:
        message: "Failed to unlock the account. Please try again or contact support."

  editor:
    nodes:
      askUsername:
        x: 200
        y: 300