description: 'A login flow with username and password, and password upgrade to passkey'
start: init
nodes:
  init:
    name: init
    use: init
    custom_config: {}
    next:
      start: passwordOrSocialLogin 
  
  # Start by asking for username/password or passkey
  passwordOrSocialLogin:
    name: passwordOrSocialLogin
    use: passwordOrSocialLogin
    custom_config:
      useUsername: true
      usePassword: true
      usePasskeys: true
    next:
      password: validatePassword
      passkey: verifyPasskey

  # Validate password
  validatePassword:
    name: validatePassword
    use: validatePassword
    custom_config: {}
    next:
      success: checkPasskeyRegistered
      fail: passwordOrSocialLogin
      locked: failureResult
      noPassword: failureResult
  
  # Check if passkey is registered, if not register it
  checkPasskeyRegistered:
    name: checkPasskeyRegistered
    use: checkPasskeyRegistered
    custom_config: {}
    next:
      registered: successResult
      not_registered: registerPasskey
      user_not_found: failureResult

  # Register passkey
  registerPasskey:
    name: registerPasskey
    use: registerPasskey
    custom_config: {}
    next:
      success: successResult
      failure: failureResult


  # Verify passkey if we have one
  verifyPasskey:
    name: verifyPasskey
    use: verifyPasskey
    custom_config: {}
    next:
      success: successResult
      failure: failureResult


  # Failure result
  failureResult:
    name: failureResult
    use: failureResult
    custom_config:
      message: Failed to login.
    next: {}
    
  # Success result
  successResult:
    name: successResult
    use: successResult
    custom_config:
      message: Login successful!
    next: {}