description: 'Login with username and password and optional upgrade to TOTP. Afterwards enforce TOTP.'
start: init
nodes:
  init:
    name: init
    use: init
    custom_config: {}
    next:
      start: askUsernamePassword 
      
  askUsernamePassword:
    name: askUsernamePassword
    use: askUsernamePassword
    custom_config:
      message: Please login to your account
    next:
      submitted: validatePassword

  validatePassword:
    name: validatePassword
    use: validatePassword
    custom_config: {}
    next:
      success: hasYubicoOtp
      fail: askUsernamePassword
      locked: failureResult
      noPassword: failureResult

  hasYubicoOtp:
    name: hasYubicoOtp
    use: hasYubicoOtp
    custom_config: {}
    next:
      yes: verifyYubikeyOtp
      no: createYubikeyOtp

  verifyYubikeyOtp:
    name: verifyYubikeyOtp
    use: verifyYubikeyOtp
    custom_config:
      yubikey-checkunique: false
    next:
      success: successResult
      fail: verifyYubikeyOtp
      locked: failureResult

  createYubikeyOtp:
    name: createYubikeyOtp
    use: createYubikeyOtp
    custom_config:
      yubikey-checkunique: false
    next:
      success: successResult
      fail: failureResult

  failureResult:
    name: failureResult
    use: failureResult
    custom_config:
      message: Failed to login.
    next: {}
    
  successResult:
    name: successResult
    use: successResult
    custom_config:
      message: Login successful!
    next: {}