description: ''
start: init
nodes:
  init:
    name: init
    use: init
    custom_config: {}
    next:
      start: askUsername
      
  askUsername:
    name: askUsername
    use: askUsername
    custom_config:
      message: Please register your account
    next:
      submitted: checkUsernameAvailable

  checkUsernameAvailable:
    name: checkUsernameAvailable
    use: checkUsernameAvailable
    custom_config: {}
    next:
      available: askPassword
      taken: registerFailed

  askPassword:
    name: askPassword
    use: askPassword
    custom_config:
      message: Please register your account
    next:
      submitted: createUser

  createUser:
    name: createUser
    use: createUser
    custom_config: {}
    next:
      fail: registerFailed
      success: registerSuccess
  
  registerFailed:
    name: failureResult
    use: failureResult
    custom_config:
      message: Failed to create user. Username may already exist.
    next: {}
    
  registerSuccess:
    name: successResult
    use: successResult
    custom_config:
      message: Registration successful!
    next: {}