description: 'Login with username and password and optional upgrade to TOTP. Afterwards enforce TOTP.'
start: init
nodes:
  init:
    name: init
    use: init
    custom_config: {}
    next:
      start: askUsernamePassword 
      
  askUsernamePassword:
    name: askUsernamePassword
    use: askUsernamePassword
    custom_config:
      message: Please login to your account
    next:
      submitted: validatePassword

  validatePassword:
    name: validatePassword
    use: validatePassword
    custom_config: {}
    next:
      success: hasTOTP
      fail: askUsernamePassword
      locked: failureResult
      noPassword: failureResult

  hasTOTP:
    name: hasTOTP
    use: hasTOTP
    custom_config: {}
    next:
      yes: verifyTOTP
      no: createTOTP

  verifyTOTP:
    name: verifyTOTP
    use: verifyTOTP
    custom_config: {}
    next:
      success: successResult
      fail: verifyTOTP
      locked: failureResult

  createTOTP:
    name: createTOTP
    use: createTOTP
    custom_config: {}
    next:
      success: successResult
      fail: failureResult

  failureResult:
    name: failureResult
    use: failureResult
    custom_config:
      message: Failed to login.
    next: {}
    
  successResult:
    name: successResult
    use: successResult
    custom_config:
      message: Login successful!
    next: {}