// Package swagger_ui Code generated by swaggo/swag. DO NOT EDIT
package swagger_ui

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/realms": {
            "get": {
                "description": "Returns a list of all available tenant/realm combinations",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Realms"
                ],
                "summary": "List all tenant/realm combinations",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/admin_api.ShortTenantInfo"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/admin/{tenant}/{realm}/": {
            "get": {
                "description": "Returns a list of all available tenant/realm combinations",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Realms"
                ],
                "summary": "List all tenant/realm combinations",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant ID",
                        "name": "tenant",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Realm ID",
                        "name": "realm",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Realm"
                        }
                    },
                    "404": {
                        "description": "Realm not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/admin/{tenant}/{realm}/dashboard": {
            "get": {
                "description": "Returns combined user stats and flow information for a tenant/realm",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Get dashboard data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant ID",
                        "name": "tenant",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Realm ID",
                        "name": "realm",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/admin_api.DashboardResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/admin/{tenant}/{realm}/users": {
            "get": {
                "description": "Get a paginated list of users",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "List users",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant ID",
                        "name": "tenant",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Realm ID",
                        "name": "realm",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "Page size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/admin_api.PagedResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/admin/{tenant}/{realm}/users/stats": {
            "get": {
                "description": "Get user statistics for the realm",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get user statistics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant ID",
                        "name": "tenant",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Realm ID",
                        "name": "realm",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.UserStats"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/admin/{tenant}/{realm}/users/{username}": {
            "get": {
                "description": "Get a specific user by username",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant ID",
                        "name": "tenant",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Realm ID",
                        "name": "realm",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "Update an existing user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Update user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant ID",
                        "name": "tenant",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Realm ID",
                        "name": "realm",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User object",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Create user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant ID",
                        "name": "tenant",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Realm ID",
                        "name": "realm",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User object",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Delete user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant ID",
                        "name": "tenant",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Realm ID",
                        "name": "realm",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/debug/flows/all": {
            "get": {
                "description": "Returns a plain text list of all authentication flows across all tenants and realms",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Debug"
                ],
                "summary": "List all flows across all tenants/realms",
                "responses": {
                    "200": {
                        "description": "List of flows in plain text format",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "description": "Returns a simple status indicating if the service is alive",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Check service liveness",
                "responses": {
                    "200": {
                        "description": "Service status",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/info": {
            "get": {
                "description": "Returns basic information about the service including version",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Get service information",
                "responses": {
                    "200": {
                        "description": "Service information",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/readyz": {
            "get": {
                "description": "Returns the readiness status of the service and its components",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Check service readiness",
                "responses": {
                    "200": {
                        "description": "Service and components readiness status",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "503": {
                        "description": "Service is not ready",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/{tenant}/{realm}/auth/{path}": {
            "get": {
                "description": "Handles authentication requests by executing the specified flow. Returns either a prompt for user input or a final result. Supports debug mode for additional information.",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Process authentication request",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant ID",
                        "name": "tenant",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Realm ID",
                        "name": "realm",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Flow path/name",
                        "name": "path",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Enable debug mode",
                        "name": "debug",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Current step in the flow",
                        "name": "step",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "User input for the current step's prompts",
                        "name": "{prompt_key}",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "HTML response containing either a prompt form or the final result",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Realm or flow not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Handles authentication requests by executing the specified flow. Returns either a prompt for user input or a final result. Supports debug mode for additional information.",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Process authentication request",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant ID",
                        "name": "tenant",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Realm ID",
                        "name": "realm",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Flow path/name",
                        "name": "path",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Enable debug mode",
                        "name": "debug",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Current step in the flow",
                        "name": "step",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "User input for the current step's prompts",
                        "name": "{prompt_key}",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "HTML response containing either a prompt form or the final result",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Realm or flow not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/{tenant}/{realm}/debug/flows": {
            "get": {
                "description": "Returns a JSON list of available authentication flows for the specified tenant and realm",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Debug"
                ],
                "summary": "List flows for a specific tenant and realm",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant ID",
                        "name": "tenant",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Realm ID",
                        "name": "realm",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of flows with name and route",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/{tenant}/{realm}/debug/{flow}/graph.png": {
            "get": {
                "description": "Generates and returns a PNG image visualization of the specified authentication flow",
                "produces": [
                    "image/png"
                ],
                "tags": [
                    "Debug"
                ],
                "summary": "Generate PNG graph of a flow",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant",
                        "name": "tenant",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Realm",
                        "name": "realm",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Flow Route",
                        "name": "flow",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "PNG image of the flow graph",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad request - missing flow parameter",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Flow not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/{tenant}/{realm}/debug/{flow}/graph.svg": {
            "get": {
                "description": "Generates and returns an SVG image visualization of the specified authentication flow",
                "produces": [
                    "image/svg+xml"
                ],
                "tags": [
                    "Debug"
                ],
                "summary": "Generate SVG graph of a flow",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant ID",
                        "name": "tenant",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Realm ID",
                        "name": "realm",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Flow name",
                        "name": "flow",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "SVG image of the flow graph",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad request - missing flow parameter",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Flow not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/{tenant}/{realm}/static/{filename}": {
            "get": {
                "description": "Serves static files (images, CSS, JavaScript, etc.) for a specific tenant and realm",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "Static"
                ],
                "summary": "Serve static files",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant ID",
                        "name": "tenant",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Realm ID",
                        "name": "realm",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Name of the static file to serve",
                        "name": "filename",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The requested static file",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "404": {
                        "description": "File not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "admin_api.DashboardResponse": {
            "type": "object",
            "properties": {
                "flows": {
                    "$ref": "#/definitions/admin_api.FlowInfo"
                },
                "user_stats": {
                    "$ref": "#/definitions/model.UserStats"
                }
            }
        },
        "admin_api.FlowInfo": {
            "type": "object",
            "properties": {
                "active_flows": {
                    "type": "integer"
                },
                "total_flows": {
                    "type": "integer"
                }
            }
        },
        "admin_api.PagedResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "pagination": {
                    "$ref": "#/definitions/admin_api.Pagination"
                }
            }
        },
        "admin_api.Pagination": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total_items": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "admin_api.ShortRealmInfo": {
            "type": "object",
            "properties": {
                "realm": {
                    "type": "string"
                },
                "realm_name": {
                    "type": "string"
                }
            }
        },
        "admin_api.ShortTenantInfo": {
            "type": "object",
            "properties": {
                "realms": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/admin_api.ShortRealmInfo"
                    }
                },
                "tenant": {
                    "type": "string"
                },
                "tenant_name": {
                    "type": "string"
                }
            }
        },
        "model.Realm": {
            "type": "object",
            "properties": {
                "realm": {
                    "description": "e.g. \"customers\"",
                    "type": "string"
                },
                "realmName": {
                    "description": "e.g. \"Our Customers\"",
                    "type": "string"
                },
                "tenant": {
                    "description": "e.g. \"acme\"",
                    "type": "string"
                }
            }
        },
        "model.User": {
            "description": "User information and attributes",
            "type": "object",
            "properties": {
                "attributes": {
                    "description": "Extensibility",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        " 'location'": " 'HQ'}",
                        "{'department'": " 'IT'"
                    }
                },
                "created_at": {
                    "description": "Audit",
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "display_name": {
                    "description": "Identity Information",
                    "type": "string",
                    "example": "John Doe"
                },
                "email": {
                    "description": "Additional contact information",
                    "type": "string",
                    "example": "john.doe@example.com"
                },
                "email_verified": {
                    "type": "boolean",
                    "example": true
                },
                "failed_login_attempts_mfa": {
                    "type": "integer",
                    "example": 0
                },
                "failed_login_attempts_password": {
                    "type": "integer",
                    "example": 0
                },
                "failed_login_attempts_webauthn": {
                    "type": "integer",
                    "example": 0
                },
                "family_name": {
                    "type": "string",
                    "example": "Doe"
                },
                "federated_id": {
                    "type": "string",
                    "example": "123456789"
                },
                "federated_idp": {
                    "description": "Federation",
                    "type": "string",
                    "example": "google"
                },
                "given_name": {
                    "type": "string",
                    "example": "John"
                },
                "groups": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "['developers'",
                        " 'support']"
                    ]
                },
                "id": {
                    "description": "Unique UUID for the user",
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "last_login_at": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "locale": {
                    "description": "Locale",
                    "type": "string",
                    "example": "en-US"
                },
                "mfa_locked": {
                    "type": "boolean",
                    "example": false
                },
                "password_locked": {
                    "type": "boolean",
                    "example": false
                },
                "phone": {
                    "type": "string",
                    "example": "+1234567890"
                },
                "phone_verified": {
                    "type": "boolean",
                    "example": false
                },
                "realm": {
                    "type": "string",
                    "example": "customers"
                },
                "roles": {
                    "description": "User roles and groups",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "['admin'",
                        " 'user']"
                    ]
                },
                "status": {
                    "description": "User status",
                    "type": "string",
                    "example": "active"
                },
                "tenant": {
                    "description": "Organization Context",
                    "type": "string",
                    "example": "acme"
                },
                "trusted_devices": {
                    "description": "Devices",
                    "type": "string",
                    "example": "device1,device2"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "username": {
                    "type": "string",
                    "example": "john.doe"
                },
                "webauthn_locked": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "model.UserStats": {
            "description": "User statistics for a realm",
            "type": "object",
            "properties": {
                "active_users": {
                    "type": "integer",
                    "example": 80
                },
                "email_verified": {
                    "type": "integer",
                    "example": 90
                },
                "federated_users": {
                    "type": "integer",
                    "example": 20
                },
                "inactive_users": {
                    "type": "integer",
                    "example": 15
                },
                "locked_users": {
                    "type": "integer",
                    "example": 5
                },
                "mfa_enabled": {
                    "type": "integer",
                    "example": 40
                },
                "phone_verified": {
                    "type": "integer",
                    "example": 70
                },
                "total_users": {
                    "type": "integer",
                    "example": 100
                },
                "webauthn_enabled": {
                    "type": "integer",
                    "example": 30
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "GoIAM Admin API",
	Description:      "This is the admin API for GoIAM identity and access management system",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
