CREATE TABLE IF NOT EXISTS applications (
    tenant TEXT NOT NULL,
    realm TEXT NOT NULL,
    client_id TEXT NOT NULL,
    client_secret TEXT NOT NULL,
    confidential BOOLEAN NOT NULL,
    consent_required BOOLEAN NOT NULL,
    description TEXT,
    allowed_scopes TEXT NOT NULL,
    allowed_grants TEXT NOT NULL,
    allowed_authentication_flows TEXT NOT NULL,
    access_token_lifetime INTEGER NOT NULL,
    refresh_token_lifetime INTEGER NOT NULL,
    id_token_lifetime INTEGER NOT NULL,
    access_token_type TEXT NOT NULL,
    access_token_algorithm TEXT,
    access_token_mapping TEXT,
    id_token_algorithm TEXT,
    id_token_mapping TEXT,
    redirect_uris TEXT,
    settings TEXT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    PRIMARY KEY (tenant, realm, client_id)
); 